[build]
publish = "/"
command = ""

[[redirects]]
from ="/thank-you"
to = "/thank-you.html"
status = 200
force = "true"

[[headers]]
for = "/*"
[headers.value]
X-Frame-Options = "DENY"
X-XSS-Protection = "1;mode=block"